# Generated by Django 5.0.6 on 2024-07-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('isbn', models.CharField(max_length=256)),
                ('available', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Library Book',
                'verbose_name_plural': 'Library Books',
                'ordering': ['author'],
                'index_together': {('isbn',)},
            },
        ),
    ]
