# Generated by Django 5.0.6 on 2024-07-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='librarybook',
            index_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='librarybook',
            unique_together={('isbn',)},
        ),
    ]
